export default [
  {
    id: 1,
    title: "accusamus beatae ad facilis cum similique qui sunt",
    image: "https://via.placeholder.com/150/92c952",
    category_id: 2,
    price: 200,

    options: [7, 6],
  },
  {
    id: 2,
    title: "reprehenderit est deserunt velit ipsam",
    image: "https://via.placeholder.com/150/771796",
    category_id: 2,
    price: 200,
    options: [4, 1],
  },
  {
    id: 3,
    title: "officia porro iure quia iusto qui ipsa ut modi",
    image: "https://via.placeholder.com/150/24f355",
    category_id: 2,
    price: 200,
    options: [2, 8],
  },
  {
    id: 4,
    title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
    image: "https://via.placeholder.com/150/d32776",
    category_id: 2,
    price: 200,
    options: [10, 1],
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    image: "https://via.placeholder.com/150/f66b97",
    category_id: 2,
    price: 200,
    options: [2, 6],
  },
  {
    id: 6,
    title: "accusamus ea aliquid et amet sequi nemo",
    image: "https://via.placeholder.com/150/56a8c2",
    category_id: 2,
    price: 200,
    options: [7],
  },
  {
    id: 7,
    title: "officia delectus consequatur vero aut veniam explicabo molestias",
    image: "https://via.placeholder.com/150/b0f7cc",
    category_id: 3,
    price: 100,
    options: [7],
  },
  {
    id: 8,
    title: "aut porro officiis laborum odit ea laudantium corporis",
    image: "https://via.placeholder.com/150/54176f",
    category_id: 3,
    price: 100,
    options: [11],
  },
  {
    id: 9,
    title: "qui eius qui autem sed",
    image: "https://via.placeholder.com/150/51aa97",
    category_id: 3,
    price: 100,
    options: [3],
  },
  {
    id: 10,
    title: "beatae et provident et ut vel",
    image: "https://via.placeholder.com/150/810b14",
    category_id: 3,
    price: 100,
    options: [6],
  },
  {
    id: 11,
    title: "nihil at amet non hic quia qui",
    image: "https://via.placeholder.com/150/1ee8a4",
    category_id: 3,
    price: 100,
    options: [1],
  },
  //   {
  //     id: 12,
  //     title:
  //       "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
  //     image: "https://via.placeholder.com/150/66b7d2",
  //   },
  //   {
  //     id: 13,
  //     title: "repudiandae iusto deleniti rerum",
  //     image: "https://via.placeholder.com/150/197d29",
  //   },
  //   {
  //     id: 14,
  //     title: "est necessitatibus architecto ut laborum",
  //     image: "https://via.placeholder.com/150/61a65",
  //   },
  //   {
  //     id: 15,
  //     title: "harum dicta similique quis dolore earum ex qui",
  //     image: "https://via.placeholder.com/150/f9cee5",
  //   },
  //   {
  //     id: 16,
  //     title: "iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt",
  //     image: "https://via.placeholder.com/150/fdf73e",
  //   },
  //   {
  //     id: 17,
  //     title: "natus doloribus necessitatibus ipsa",
  //     image: "https://via.placeholder.com/150/9c184f",
  //   },
  //   {
  //     id: 18,
  //     title: "laboriosam odit nam necessitatibus et illum dolores reiciendis",
  //     image: "https://via.placeholder.com/150/1fe46f",
  //   },
  //   {
  //     id: 19,
  //     title: "perferendis nesciunt eveniet et optio a",
  //     image: "https://via.placeholder.com/150/56acb2",
  //   },
  //   {
  //     id: 20,
  //     title:
  //       "assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error",
  //     image: "https://via.placeholder.com/150/8985dc",
  //   },
  //   {
  //     id: 21,
  //     title: "ad et natus qui",
  //     image: "https://via.placeholder.com/150/5e12c6",
  //   },
  //   {
  //     id: 22,
  //     title: "et ea illo et sit voluptas animi blanditiis porro",
  //     image: "https://via.placeholder.com/150/45601a",
  //   },
  //   {
  //     id: 23,
  //     title: "harum velit vero totam",
  //     image: "https://via.placeholder.com/150/e924e6",
  //   },
  //   {
  //     id: 24,
  //     title: "beatae officiis ut aut",
  //     image: "https://via.placeholder.com/150/8f209a",
  //   },
];
