export default [
  {
    id: 1,
    title: "accusamus beatae ad facilis cum similique qui sunt",
    image: "https://via.placeholder.com/150/92c952",
    category_id: 2,
    price: 200,

    options: [7, 6],
  },
  {
    id: 2,
    title: "reprehenderit est deserunt velit ipsam",
    image: "https://via.placeholder.com/150/771796",
    category_id: 2,
    price: 200,
    options: [4, 1],
  },
  {
    id: 3,
    title: "officia porro iure quia iusto qui ipsa ut modi",
    image: "https://via.placeholder.com/150/24f355",
    category_id: 2,
    price: 200,
    options: [2, 8],
  },
  {
    id: 4,
    title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
    image: "https://via.placeholder.com/150/d32776",
    category_id: 2,
    price: 200,
    options: [10, 1],
  },
  {
    id: 5,
    title: "natus nisi omnis corporis facere molestiae rerum in",
    image: "https://via.placeholder.com/150/f66b97",
    category_id: 2,
    price: 200,
    options: [2, 6],
  },
  {
    id: 6,
    title: "accusamus ea aliquid et amet sequi nemo",
    image: "https://via.placeholder.com/150/56a8c2",
    category_id: 2,
    price: 200,
    options: [7],
  },
  {
    id: 7,
    title: "officia delectus consequatur vero aut veniam explicabo molestias",
    image: "https://via.placeholder.com/150/b0f7cc",
    category_id: 3,
    price: 100,
    options: [7],
  },
  {
    id: 8,
    title: "aut porro officiis laborum odit ea laudantium corporis",
    image: "https://via.placeholder.com/150/54176f",
    category_id: 3,
    price: 100,
    options: [11],
  },
  {
    id: 9,
    title: "qui eius qui autem sed",
    image: "https://via.placeholder.com/150/51aa97",
    category_id: 3,
    price: 100,
    options: [3],
  },
  {
    id: 10,
    title: "beatae et provident et ut vel",
    image: "https://via.placeholder.com/150/810b14",
    category_id: 3,
    price: 100,
    options: [6],
  },
  {
    id: 11,
    title: "nihil at amet non hic quia qui",
    image: "https://via.placeholder.com/150/1ee8a4",
    category_id: 3,
    price: 100,
    options: [1],
  },
];
